title: "Building, managing, and running containers using GitHub Actions, DockerHub, and container-mod"
description: "Container workshop provided by Tufts Research Technology"

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - hands-on/
encoding: UTF-8
